import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CookiesProvider } from "next-client-cookies/server";
import { cookies } from "next/headers";
import { Theme } from "@/app/types/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = cookies().get("theme")?.value as Theme;

  return (
    <html lang="en" className={theme ?? ""}>
      <body>
        <CookiesProvider>{children}</CookiesProvider>
      </body>
    </html>
  );
}
